INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Dönertasche klein", 3.5, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Dönertasche groß", 6.5, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Dürüm", 3.9, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Dönertasche", 3.8, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Döner mit Salat", 5.9, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Döner mit Pommes", 5.9, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Dönerteller", 7.0, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Iskender Kebap", 8.0, "Döner Gerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Lahmacun klein", 2.5, "Lahmacun", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Lahmacun mittel", 3.5, "Lahmacun", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Lahmacun groß", 4.8, "Lahmacun", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Salat Tasche", 3.0, "Vegetarisch", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Falafeltasche", 3.3, "Vegetarisch", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Falafel Dürüm", 3.7, "Vegetarisch", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Falafel Teller", 6.0, "Vegetarisch", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Döner überbacken Zaziki", 6.5, "Döner überbacken", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Döner überbacken Holandaise", 6.5, "Döner überbacken", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Pommes klein", 1.4, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Pommes groß", 2.4, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Pommes Spezial klein", 2.4, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Pommes Spezial groß", 3.8, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Kroketten", 1.5, "Imbissgerichte", "6 Stück");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Bratwurst", 1.7, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Currywurst", 2.0, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Jägerwurst", 2.3, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Zigeunerwurst", 2.3, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Hamburger", 2.0, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Cheeseburger", 2.5, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Chicken Nuggets", 3.5, "Imbissgerichte", "6 Stück");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Jägersauce", 0.6, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Zigeunersauce", 0.6, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Ketchup", 0.4, "Imbissgerichte", "");
INSERT INTO doener_artikel (name, preis, kategorie, beschreibung) values ("Majo", 0.4, "Imbissgerichte", "");												
